channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- dill =0.3.4
- future =0.18.2
- gitpython =3.1.25
- h5io =0.1.4
- h5py =3.6.0
- numpy =1.22.0
- pandas =1.3.5
- pathlib2 =2.3.6
- pint =0.18
- psutil =5.9.0
- pyfileindex =0.0.6
- pysqa =0.0.15
- pytables =3.6.1
- sqlalchemy =1.4.29
- tqdm =4.62.3
