channels:
- conda-forge
dependencies:
- sphinx
- nbsphinx
- ipywidgets
- sphinx_rtd_theme
- pylint
- Graphviz
- sphinxcontrib-applehelp
- seaborn
- jinja2
- dill
- future
- gitpython
- h5io
- h5py
- numpy
- pandas
- pathlib2
- pint
- psutil
- pyfileindex
- pysqa
- pytables
- sqlalchemy
- tqdm
