# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Compatibility with pyiron_atomistics

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8
        channel-priority: strict
        environment-file: .ci_support/environment.yml
    - name: Setup
      shell: bash -l {0}
      run: |
        python .ci_support/pyironconfig.py
        pip install --no-deps .
        conda env update --name test --file .ci_support/environment-notebooks.yml
        mkdir -p tests/compat
        git clone https://github.com/pyiron/pyiron_atomistics tests/compat/atomistics
        cd  tests/compat/atomistics
        conda env update --name test --file .ci_support/environment.yml
        python .ci_support/pyironconfig.py
        pip install --no-deps .
    - name: Test
      shell: bash -l {0}
      run: |
        cd tests/compat/atomistics
        python -m unittest discover tests/
