# This workflow is used to run benchmarktests based on the unittest framework

name: Benchmark tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  benchmark:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10"
        mamba-version: "*"
        channels: conda-forge
        channel-priority: strict
        auto-update-conda: true  
        environment-file: .ci_support/environment.yml
    - name: Setup
      shell: bash -l {0}
      run: |
        python .ci_support/pyironconfig.py
        pip install --no-deps .
    - name: Tests
      shell: bash -l {0}
      timeout-minutes: 30
      run: python -m unittest discover test_benchmarks
