# This workflow is used to check the compatibility with the pyiron_contrib

name: Compatibility with pyiron_contrib

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [labeled, opened, synchronize, reopened]

jobs:
  build:
    if: |
      github.event_name == 'push' ||
      ( github.event_name == 'pull_request'  && contains(github.event.pull_request.labels.*.name, 'integration' ))
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: pyiron_contrib
      run: |
        pip install PyYAML
        git clone https://github.com/pyiron/pyiron_contrib ../pyiron_contrib
        grep -v "pyiron_base" ../pyiron_contrib/.ci_support/environment.yml > ../pyiron_contrib/environment.yml
        python .ci_support/condamerge.py --base .ci_support/environment.yml --add ../pyiron_contrib/environment.yml > environment.yml
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10"
        mamba-version: "*"
        channels: conda-forge
        channel-priority: strict
        auto-update-conda: true  
        environment-file: environment.yml
    - name: pyironconfig
      shell: bash -l {0}
      run: |
        cd ../pyiron_contrib
        python .ci_support/pyironconfig.py
        cd ../pyiron_base
    - name: Install pyiron_contrib
      shell: bash -l {0}
      run: |
        cd ../pyiron_contrib
        pip install --no-deps .
        cd ../pyiron_base
    - name: Install pyiron_base
      shell: bash -l {0}
      run: |
        pip install --no-deps .
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 30
      run: |
        cd ../pyiron_contrib
        python -m unittest discover tests/
